const pool=require('../db');const config=require('../config');const storage=require('./storage');const {parseCanonicalWav}=require('../lib/wav');const {generateVtt}=require('../lib/captions');const {appendAudit,sha256}=require('./audit');
let timer=null;let working=false;
async function transaction(work){const client=await pool.connect();try{await client.query('BEGIN');const result=await work(client);await client.query('COMMIT');return result;}catch(error){await client.query('ROLLBACK').catch(()=>{});throw error;}finally{client.release();}}
async function claim(jobId){return transaction(async(client)=>{const row=(await client.query(`SELECT j.*,v.project_id,v.object_key,v.captions_key,v.transcript,v.content_sha256,v.created_by FROM media_jobs j JOIN media_versions v ON v.id=j.version_id WHERE j.id=$1 FOR UPDATE OF j,v`,[jobId])).rows[0];if(!row||row.status!=='QUEUED')return null;if(row.cancellation_requested){await client.query("UPDATE media_jobs SET status='CANCELLED',finished_at=NOW(),updated_at=NOW() WHERE id=$1",[jobId]);await client.query("UPDATE media_versions SET processing_state='CANCELLED',updated_at=NOW() WHERE id=$1",[row.version_id]);return null;}await client.query("UPDATE media_jobs SET status='RUNNING',attempts=attempts+1,started_at=NOW(),updated_at=NOW(),error_code=NULL,error_message=NULL WHERE id=$1",[jobId]);await client.query("UPDATE media_versions SET processing_state='PROCESSING',updated_at=NOW() WHERE id=$1",[row.version_id]);return row;});}
async function failJob(row,error){const allowed=new Set(['OBJECT_CHECKSUM_MISMATCH','INVALID_WAV','MEDIA_TOO_LARGE','MEDIA_TOO_LONG']);const code=allowed.has(error.code)?error.code:'PROCESSING_FAILED';const message=code==='PROCESSING_FAILED'?'Stored media object is unavailable or invalid':String(error.message||'Media processing failed').slice(0,500);await transaction(async(client)=>{const current=(await client.query('SELECT status FROM media_jobs WHERE id=$1 FOR UPDATE',[row.id])).rows[0];if(!current||current.status!=='RUNNING')return;await client.query("UPDATE media_jobs SET status='FAILED',error_code=$2,error_message=$3,finished_at=NOW(),updated_at=NOW() WHERE id=$1",[row.id,code,message]);await client.query("UPDATE media_versions SET processing_state='FAILED',updated_at=NOW() WHERE id=$1",[row.version_id]);await appendAudit(client,{projectId:row.project_id,versionId:row.version_id,actorUserId:row.created_by,action:'MEDIA_PROCESSING_FAILED',outcome:'FAILED',metadata:{jobId:Number(row.id),errorCode:code}});});}
async function processJob(jobId){const row=await claim(jobId);if(!row)return{processed:false};try{const buffer=await storage.read(row.object_key);const metadata=parseCanonicalWav(buffer,{maxBytes:config.maxUploadBytes,maxDurationSeconds:config.maxDurationSeconds});if(sha256(buffer)!==row.content_sha256){const error=new Error('Stored media checksum mismatch');error.code='OBJECT_CHECKSUM_MISMATCH';throw error;}const captionsKey=`captions/${row.version_id}.vtt`;await storage.atomicWrite(captionsKey,generateVtt(row.transcript,metadata.durationMs));const result=await transaction(async(client)=>{const current=(await client.query('SELECT * FROM media_jobs WHERE id=$1 FOR UPDATE',[row.id])).rows[0];if(current.cancellation_requested){await storage.remove(captionsKey).catch(()=>{});await client.query("UPDATE media_jobs SET status='CANCELLED',finished_at=NOW(),updated_at=NOW() WHERE id=$1",[row.id]);await client.query("UPDATE media_versions SET processing_state='CANCELLED',updated_at=NOW() WHERE id=$1",[row.version_id]);await appendAudit(client,{projectId:row.project_id,versionId:row.version_id,actorUserId:row.created_by,action:'MEDIA_PROCESSING_CANCELLED',outcome:'CANCELLED',metadata:{jobId:Number(row.id)}});return{processed:false,cancelled:true};}await client.query("UPDATE media_versions SET processing_state='READY',captions_key=$2,sample_rate_hz=$3,channel_count=$4,bit_depth=$5,duration_ms=$6,updated_at=NOW() WHERE id=$1",[row.version_id,captionsKey,metadata.sampleRateHz,metadata.channelCount,metadata.bitDepth,metadata.durationMs]);await client.query("UPDATE media_jobs SET status='SUCCEEDED',finished_at=NOW(),updated_at=NOW() WHERE id=$1",[row.id]);await appendAudit(client,{projectId:row.project_id,versionId:row.version_id,actorUserId:row.created_by,action:'MEDIA_PROCESSING_SUCCEEDED',metadata:{jobId:Number(row.id),sampleRateHz:metadata.sampleRateHz,channelCount:metadata.channelCount,bitDepth:metadata.bitDepth,durationMs:metadata.durationMs,contentSha256:row.content_sha256}});return{processed:true,metadata};});return result;}catch(error){await failJob(row,error);return{processed:false,failed:true,code:error.code||'PROCESSING_FAILED'};}}
async function recover(){await pool.query(`UPDATE media_jobs SET status=CASE WHEN attempts<max_attempts THEN 'QUEUED' ELSE 'FAILED' END,error_code='WORKER_INTERRUPTED',error_message='Worker lease expired',updated_at=NOW() WHERE status='RUNNING' AND started_at<NOW()-INTERVAL '5 minutes'`);await pool.query(`UPDATE media_versions v SET processing_state=CASE WHEN j.status='QUEUED' THEN 'QUEUED' ELSE 'FAILED' END,updated_at=NOW() FROM media_jobs j WHERE j.version_id=v.id AND j.error_code='WORKER_INTERRUPTED'`);}
async function tick(){if(working)return;working=true;try{const row=(await pool.query("SELECT id FROM media_jobs WHERE status='QUEUED' ORDER BY created_at LIMIT 1")).rows[0];if(row)await processJob(row.id);}finally{working=false;}}
async function startWorker(){if(!config.workerEnabled||timer)return;await storage.ensureRoot();await recover();timer=setInterval(()=>tick().catch((error)=>console.error(JSON.stringify({level:'error',event:'worker_tick_failed',message:error.message}))),1000);timer.unref();setImmediate(()=>tick().catch(()=>{}));}
function stopWorker(){if(timer){clearInterval(timer);timer=null;}}
module.exports={processJob,recover,startWorker,stopWorker};
